# Generated by Django 2.1.7 on 2019-02-27 18:16

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary mobile number e.g. +91{10 digit mobile number}', max_length=128, unique=True, verbose_name='Mobile Number'),
        ),
    ]
