# Generated by Django 2.1.7 on 2019-02-27 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'credit'), ('debit', 'debit')], default='debit', max_length=10, verbose_name='Transaction Type')),
                ('txn_no', models.CharField(max_length=10, verbose_name='Transaction Number')),
                ('status', models.CharField(choices=[('success', 'success'), ('failure', 'failure'), ('pending', 'pending')], default='pending', max_length=10, verbose_name='Status')),
                ('amount', models.FloatField(default=0.0, verbose_name='Transaction Amount')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.Wallet')),
            ],
            options={
                'verbose_name': 'Transaction Order',
                'verbose_name_plural': 'Transaction Orders',
            },
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('txn_no', 'wallet')},
        ),
    ]
